### PR TITLE
Added support for laravel 10

### PR DESCRIPTION
**Pull request by zayedadel**

### CODE REVIEW

**Comment by vonec** [comment]
kindly merge this commit been waiting for so long

**Comment by dinandmentink** [comment]
@tihomiro Is this project still maintained? Kindly merge one of the multiple laravel v10 pull requests.

**Comment by vonec** [comment]
is the new version released ?

**Comment by vonec** [comment]
thank you ... :) thanks a lot

**Comment by dinandmentink** [comment]
Thanks!

**Comment by Javier1995** [comment]
Thanks!

**Pull request merged**
