### PR TITLE
multiple database bug error

### PR DESCRIPTION
**Pull request by choiks14**
multiple database bug error
Update config Schema's connection.

### CODE REVIEW

**Comment by NightfallSD** [comment]
Hi choiks14. Thx for your pull request.

If I understood it correctly you are forcing seed files to seed only connection from whom they were generated. I'm not certain that is useful feature. For example, what if someone wants to seed db using data from some other connection? 

Why not just use --database option when executing php artisan db:seed?

**Comment by choiks14** [comment]
i use oauth server.so i want to use iseed for multiple database.

resource data and oauth data.

and my english is poor sorry...

**Comment by choiks14** [comment]
is it rejected?

**Comment by NightfallSD** [comment]
Yes it is. As I said, functionality you implemented already exists. When you want to seed specific db using seeds generated with iseed you can run this command in console: 

php artisan db:seed --database=connectionName

**Pull request closed without merging**
