### PR TITLE
Support laravel 8 by default

### PR DESCRIPTION
**Pull request by dinandmentink**
Related to #166 

This PR aims to support laravel 8 by default. To do this the following changes are made:

1. Add `namespace Database\Seeders;` namespace to the seed stub.
2. Change config to point to the default `database/seeders/` directory over the laravel 7 `database/seeds`
3. Change the `Stubs` directory to `stubs`

With regards to 3: 

The default laravel stubs dir is called `stubs`, for iSeed this is `Stubs`. I would like to rename this as to make changing the seed stub easier. 

I strongly suspect this pr requires a major version bump.

### CODE REVIEW

**Comment by dinandmentink** [comment]
phpunit tests are green.

**Comment by powellblyth** [comment]
Hiya, there's a substantial difference between L7 and L8 seeders. 

Running iseed on a vanilla L8 installation gives this message without this PR
`
   ErrorException 

  file_put_contents(/var/www/html/database/seeds/DomainHistoriesTableSeeder.php): failed to open stream: No such file or directory

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:185
    181▕      * @return int|bool
    182▕      */
    183▕     public function put($path, $contents, $lock = false)
    184▕     {
  ➜ 185▕         return file_put_contents($path, $contents, $lock ? LOCK_EX : 0);
    186▕     }
    187▕ 
    188▕     /**
    189▕      * Write the contents of a file, replacing it atomically if it already exists.

      +18 vendor frames 
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))`

**Review by yazeed — APPROVED** [review]
Looks good.

**Review by GoodJob — COMMENTED** [review]
Is this already pushed to the stable version? Because still getting an error of "file_put_contents" after fresh Laravel 8 install today

**Review by GoodJob — APPROVED** [review]
Is this already pushed to the stable version? Because still getting an error of "file_put_contents" after fresh Laravel 8 install today

**Comment by agarwalvaibhav0211** [comment]
Code is good

**Comment by GoodJob** [comment]
Waiting so much for official fix 🧘🏻‍♂️

**Comment by dinandmentink** [comment]
Thanks for merging!

**Pull request merged**
