### PR TITLE
Test

### PR DESCRIPTION
**Pull request by Qh0stM4N**
Open testing merging fork for #58 based #73 and #76 pr basd from @PaulVisscher master branch

### CODE REVIEW

**Comment by Qh0stM4N** [comment]
ref URL: https://github.com/orangehill/iseed/issues/58#issuecomment-269732160
Experimental not finised yet.

**Comment by kevin1193** [comment]
Hi, is the see all tables functionality already merged? Thanks

**Comment by Qh0stM4N** [comment]
@kevin1193 not merged 2 pr closed by maintainer. I'll finish this PR when I'm available. 
sorry i do not know when i can make, and help wanted with CI

**Comment by tihomiro** [comment]
I'm not sure what the status of this PR is... apparently still has issues with CI. Gonna close this for now so if you manage to get it to pass the CI tests please submit another pull request.

**Comment by Qh0stM4N** [comment]
@tihomiro thanks this PR same as PR name.  When i finish, will make a new request.

**Pull request closed without merging**
