### PR TITLE
add a new optional input  "orderby"

### PR DESCRIPTION
**Pull request by g9308370**
hi
I need to generate the last 100 records from table.
so I add a new option input "orderby".

ex:
```
$ php artisan iseed users --force --max=100 --orderby=id
```
will generate seed file from users table and order by id DESC

### CODE REVIEW

**Comment by archfrog** [comment]
I think there is missing an option to specify direction.  --orderby should probably default to ascending (ASC) and then another option, say --direction=desc, should specify that the sort order is descending.

**Comment by g9308370** [comment]
```
php artisan iseed users --force --max=10 --orderby=id --direction=desc
```

add direction -> default to ascending (ASC)

**Comment by archfrog** [comment]
Great, thanks! :-)

**Comment by tihomiro** [comment]
This looks nice guys, thanks. I will test & merge in the next couple of days.

**Comment by tihomiro** [comment]
@g9308370 This works great, thanks again.

**Pull request merged**
