### PR TITLE
Support for Laravel 10

### PR DESCRIPTION
**Pull request by robertmarney**
Its been about a year since the last update so not sure if this is still being maintained. If it is please consider this PR to bring the package into support for the current version of Laravel.

This is a branch that intentionally stops compatibility for language versions and framework versions that is outside of support.

No changes to outputs or features.

### CODE REVIEW

**Comment by jquirogaa** [comment]
It would be nice to have this merged into master

**Comment by benbjurstrom** [comment]
Tried to use this fork but had a bunch of issues with the types when using the following command.

```bash
artisan iseed my_table_name --orderby=created_at --direction=asc --dumpauto=false --force
```

Errors like
```bash
Orangehill\Iseed\Iseed::generateSeed(): Argument #5 ($max) must be of type string|int, null given, called in /Volumes/www/mealpractice/web/vendor/orangehill/iseed/src/Orangehill/Iseed/IseedCommand.php on line 88
```

**Comment by robertmarney** [comment]
> Tried to use this fork but had a bunch of issues with the types when using the following command.
> 
> ```shell
> artisan iseed my_table_name --orderby=created_at --direction=asc --dumpauto=false --force
> ```
> 
> Errors like
> 
> ```shell
> Orangehill\Iseed\Iseed::generateSeed(): Argument #5 ($max) must be of type string|int, null given, called in /Volumes/www/mealpractice/web/vendor/orangehill/iseed/src/Orangehill/Iseed/IseedCommand.php on line 88
> ```

Hey @benbjurstrom  - Just pushed a fix and added an integration test to confirm the fix as well as to set up easier testing in future.... The original version of this had extremely loose and sometimes incorrect typing in the doc tags, was trying to cleanup for future users / maintainers.

**Comment by bhaviljain68** [comment]
hey @robertmarney @benbjurstrom ... I could really use your help here...

**Comment by robertmarney** [comment]
`composer.json`
```json
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/robertmarney/iseed/"
    },
  ],
```
`...require-dev:`

```
"orangehill/iseed": "dev-master",
```

**Comment by bhaviljain68** [comment]
> ```json
> "orangehill/iseed": "dev-master",
> ```

Hey @robertmarney ... thanks for this...can confirm that it's working ``` sail artisan iseed users ``` :)

**Pull request closed without merging**
