### PR TITLE
Laravel 6.0 support

### LINKED ISSUE #144: Add support for Laravel 6.0
Please add support for Laravel 6.0
Thanx

### PR DESCRIPTION
**Pull request by nuernbergerA**
Fixes #144

### CODE REVIEW

**Comment by nuernbergerA** [comment]
Closes #147 aswell

**Comment by nuernbergerA** [comment]
@tihomiro last commit should fix [travis error](https://travis-ci.org/orangehill/iseed/builds/582656074)

**Comment by nuernbergerA** [comment]
https://travis-ci.org/orangehill/iseed/builds/582665577

**Comment by tihomiro** [comment]
@nuernbergerA thanks for the PR!

**Pull request merged**
