### PR TITLE
add functionality to seed all tables

### PR DESCRIPTION
**Pull request by ACmagic**
as per the request of #58

### CODE REVIEW

**Comment by bertalanimre** [comment]
So what is the command to iseed back all the tables?

**Comment by ACmagic** [comment]
just php artisan iseed

**Comment by tihomiro** [comment]
Closing. More info: https://github.com/orangehill/iseed/issues/58#issuecomment-268492946

**Comment by kevin1193** [comment]
When I run php artisan iseed its looking for table parameters. Is there any work around for this?

**Comment by wimurk** [comment]
It doesn't work at all. missing tables

**Comment by Ripeplantain** [comment]
php artisan iseed --force <tablenames seperated with a comma should work>

**Pull request closed without merging**
